"$schema" = "https://starship.rs/config-schema.json"

# Timeout for commands executed by starship (ms)
command_timeout = 1000

# Newline between prompt lines
add_newline = true

format = """
$directory\
$git_branch\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"

[git_branch]
format = "\\([$branch]($style)\\) "
style = "bold red"
